import type { InventoryVariant } from "@/lib/inventory-types"
import { demoProductImageUrl } from "@/lib/demo-product-images"

export const DEMO_VARIANTS: InventoryVariant[] = [
  {
    id: "v1",
    productName: "Ergo Chair Pro",
    sku: "FURN-001",
    attributes: "Mesh / Graphite",
    onHand: 48,
    reserved: 6,
    inbound: 20,
    weeksCover: 3.2,
    trendScore: 72,
    imageUrl: demoProductImageUrl("demo:FURN-001:v1"),
  },
  {
    id: "v2",
    productName: "Ergo Chair Pro",
    sku: "FURN-001-L",
    attributes: "Leather / Sand",
    onHand: 12,
    reserved: 4,
    inbound: 0,
    weeksCover: 1.1,
    trendScore: 58,
    imageUrl: demoProductImageUrl("demo:FURN-001-L:v2"),
  },
  {
    id: "v3",
    productName: "Standing Desk Frame",
    sku: "FURN-210",
    attributes: "Black / Dual motor",
    onHand: 86,
    reserved: 22,
    inbound: 40,
    weeksCover: 4.5,
    trendScore: 81,
    imageUrl: demoProductImageUrl("demo:FURN-210:v3"),
  },
  {
    id: "v4",
    productName: "Monitor Arm 32\"",
    sku: "ACC-884",
    attributes: "Silver / Gas spring",
    onHand: 140,
    reserved: 18,
    inbound: 60,
    weeksCover: 5.8,
    trendScore: 64,
    imageUrl: demoProductImageUrl("demo:ACC-884:v4"),
  },
  {
    id: "v5",
    productName: "USB-C Dock Gen2",
    sku: "EL-442",
    attributes: "100W / Mac certified",
    onHand: 9,
    reserved: 2,
    inbound: 24,
    weeksCover: 0.9,
    trendScore: 91,
    salesQty90d: 420,
    imageUrl: demoProductImageUrl("demo:EL-442:v5"),
  },
  {
    id: "v6",
    productName: "Legacy Mouse Mat",
    sku: "ACC-OLD-01",
    attributes: "Discontinued",
    onHand: 800,
    reserved: 0,
    inbound: 0,
    weeksCover: 14,
    trendScore: 22,
    imageUrl: demoProductImageUrl("demo:ACC-OLD-01:v6"),
  },
]
